### ISSUE TITLE
`<class:Configuration>': uninitialized constant ActiveAdmin::Settings

### ISSUE THREAD

**Issue by ecmanriquejrdev** [holyketzer/activeadmin-audit#15]
I encountered this after rails g active_admin_audit:install User

/home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/active_admin/audit/configuration.rb:4:in `<class:Configuration>': uninitialized constant ActiveAdmin::Settings
Did you mean?  ActiveAdmin::SettingsNode (NameError)
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/active_admin/audit/configuration.rb:3:in `<module:Audit>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/active_admin/audit/configuration.rb:2:in `<module:ActiveAdmin>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/active_admin/audit/configuration.rb:1:in `<main>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/active_admin/audit.rb:2:in `<main>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/activeadmin-audit-0.1.4/lib/activeadmin/audit.rb:1:in `<main>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:23:in `block in require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/loaded_features_index.rb:92:in `register'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:22:in `require_with_bootsnap_lfi'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bootsnap-1.7.6/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:31:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:77:in `rescue in block in require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:55:in `block in require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `each'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.24/lib/bundler/runtime.rb:48:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/bundler-2.2.24/lib/bundler.rb:174:in `require'
	from /home/donjuanito/workspace/helpdesk/config/application.rb:9:in `<top (required)>'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `require'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:92:in `preload'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:157:in `serve'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:145:in `block in run'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `loop'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application.rb:139:in `run'
	from /home/donjuanito/.rvm/gems/ruby-3.0.0/gems/spring-2.1.1/lib/spring/application/boot.rb:19:in `<top (required)>'
	from <internal:/home/donjuanito/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from <internal:/home/donjuanito/.rvm/rubies/ruby-3.0.0/lib/ruby/3.0.0/rubygems/core_ext/kernel_require.rb>:85:in `require'
	from -e:1:in `<main>'

**Comment by holyketzer** [comment]
Looks like ActiveAdmin has changed significantly since this gem was created. You can try it with `activeadmin` `v1.3.1` or less.
